### ISSUE TITLE
gcc: isl and cloog as new dependencies

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#10]
The issue started with a careless mistake of excluding `isl` and `cloog` from the Core package list. Our `gcc` package should depend on `isl` and `cloog` as we specified in the build configuration.
### What does isl and cloog do for gcc?

> CLooG is the code generation library that is used in the Graphite loop transforms pass of GCC. GCC 4.4 uses the CLooG-PPL branch of CLooG that implements a backend of CLooG for the PPL.

As per described by GCC Wiki. http://gcc.gnu.org/wiki/CLooG

And `isl` is a dependency of cloog.
### A way to fix

Introduce `cloog` and `isl` as two new packages to the "Core". As `cloog` and `isl` are only dependent on `gmp`, which is already in the "Core".

**Comment by Artoria2e5** [comment]
Maybe it's time to create `group/core-runtime-only`.

**Comment by MingcongBai** [comment]
@Arthur2e5 Yes, and `group/core-full` too (needless to say).

**Comment by MingcongBai** [comment]
Removed `cloog` and `isl` backend support. https://github.com/AOSC-Dev/aosc-os-core/commit/6e00468a7ea35d88307dea740c95a03491b82571.

**Comment by MingcongBai** [comment]
Fixed as of https://github.com/AOSC-Dev/aosc-os-core/commit/c403b6a246d82ad19a87c76656dcbe28d47597a8.
