### ISSUE TITLE
glibc-misc: C.UTF-8

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#11]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=636086

**Comment by MingcongBai** [comment]
``` Makefile
if [ $(curpass) = libc ]; then \
        I18NPATH=$(CURDIR)/localedata GCONV_PATH=$(DEB_BUILDDIR)/iconvdata localedef --quiet -c -f UTF-8 -i C $(CURDIR)/build-tree/C.UTF-8 ; \
fi
```

Observed from `debian/rules.d/build.mk` of https://packages.debian.org/source/sid/glibc.

**Comment by MingcongBai** [comment]
However, `C` is an internal locale which cannot be processed by `localedef`... this is not making sense to me.

**Comment by MingcongBai** [comment]
@Arthur2e5 I found the patch `locale-C.diff` from the archive, now that explains why then can work with the `C` locale...

**Comment by MingcongBai** [comment]
A 390K lines patch. Now `locale-gen` package needs to be addressed to add the new locale.

**Comment by MingcongBai** [comment]
Added patch and tested from https://github.com/AOSC-Dev/aosc-os-core/commit/4b08eb6e208b5532fd3de6a6e249e81c000ac215. 

Responsibility of Core has finished. Will add another issue in AOSC-Dev/aosc-os-abbs.

**Comment by Artoria2e5** [comment]
Ah Bai, so are we doing `localedef --quiet -c -f UTF-8 -i C $PKGDIR/usr/lib/locale/C.UTF-8` now?

**Comment by MingcongBai** [comment]
> Ah Bai, so are we doing localedef --quiet -c -f UTF-8 -i C $PKGDIR/usr/lib/locale/C.UTF-8 now?

No, I am still in question of how `locale-gen` will work, currently it is a single file `/usr/lib/locale/locale-archive`.

**Comment by MingcongBai** [comment]
> No, I am still in question of how locale-gen will work, currently it is a single file /usr/lib/locale/locale-archive.

I brain-farted, just change the last parameter to `/usr/lib/locale/locale-archive`.
