### ISSUE TITLE
gcc: bump to 5.3

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#16]
```
December 4, 2015

The GNU project and the GCC developers are pleased to announce the release of GCC 5.3.

This release is a bug-fix release, containing fixes for regressions in GCC 5.2 relative to previous releases of GCC.
```

The new Core release should bump to this version, as GCC 5.x is yet to be more mature, and some packages in `aosc-os-abbs` tree is having issue with the new compiler (`wine` is a good example), and is known to be fixed by this release.

**Comment by Artoria2e5** [comment]
Wheeeee!
