### ISSUE TITLE
glibc: should depend on linux+api

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#19]
If a package is to be provided with its respective headers, so should `glibc`. `glibc` when not dependent on `linux+api` is practically useless in a development scenario.

**Comment by Artoria2e5** [comment]
But does it DEPEND on `linux+api` technically? We should change the magic bullet dev metapackage autobuild instead.

**Comment by Icenowy** [comment]
The development part of glibc does depend on linux+api.

(musl do not have this dependency... interesting)
- 发送自我的Sony Xperia™智能手机

---- Mingye Wang编写 ----

But does it DEPEND on `linux+api` technically? We should change the magic bullet dev metapackage autobuild instead.

---

**Comment by Artoria2e5** [comment]
Sigh. Sad story with non-splitting.
