### ISSUE TITLE
infrastructure: shall we add a set of busybox commands to aosc-os-core?

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#2]
Here are some definitions for the busybox package:

``` Bash
# part of defines
PKGNAME=busybox
PKGPROV=sh
```

``` Bash
# overrides/etc/profile.d/80-busybox
export PATH="$PATH:/busybin"
```

Busybox here is chosen to be placed in `/busybin` so we can use it even if `/usr` is on a seperate dir, maintaining the possiblity of using no `initramfs` at all (for init scripts, we can `mount --bind /busybin /bin` first and in the end recover the symlink.)

**Comment by MingcongBai** [comment]
As of now, still pending discussion.

**Comment by MingcongBai** [comment]
Refer to #23 for future discussions.
