### ISSUE TITLE
core: merge build scripts

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#21]
Time to merge the `build` files into a single `defines`. Given that:
- It is way too much trouble changing stuff for each version change;
- It did not help readability anyways;

**Comment by Artoria2e5** [comment]
If some of you guys don't fscking trust ab3 yet, I'd rather have you use something like this in a unified build:

``` sh
case $ARCH in
  shit)
    clean-after-shit
    ;;
  crap)
    fix-crap-glibc-version
    ;;
esac
```

Hopefully this will make you think twice.

As an aside, if you still don't know how to quote or store options, go to http://shellcheck.net and http://mywiki.wooledge.org/BashGuide/Arrays.

**Comment by MingcongBai** [comment]
Quit, spilling, crap.

I will fix them as I have started the issue, there is **absolutely** no point in keep attacking on this issue. If you can't even wait for a second, fix it yourself. I have no problem cleaning up after you.

Thanks.

**Comment by Artoria2e5** [comment]
Even diff knows how many dups there are…

**Comment by MingcongBai** [comment]
All done. I can start test the build now.

**Comment by Artoria2e5** [comment]
All the `$ARCH` should be `${CROSS:-ARCH}` before AOSC-Dev/autobuild#83. After the patch, replace them with `$ABHOST` or `$CROSS`.

**Comment by MingcongBai** [comment]
Core 3.5 released with this change. Yay!

**Comment by Artoria2e5** [comment]
……Ugh Bai
Not ARCH.
$CROSS.

For current AB,
`${CROSS:-$ARCH}`.

**Comment by Artoria2e5** [comment]
Reopened due to predicted bugs.

**Comment by MingcongBai** [comment]
All done. Including double brackets for glob matching.
