### ISSUE TITLE
db: deprecate package

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#22]
Berkeley DB 6.x is licensed under AGPL, as you can read here.

http://www.gnu.org/licenses/agpl-3.0.en.html

However, the license as it stands, may lead to potential licensing issues. Also, given that no package in the Core really needs `db`, and packages in AOSC OS (~20 packages) are due to be cut from `db` in the near future, `db` should be deprecated as a component of Core, and to be moved to `base-databases`.

**Comment by Artoria2e5** [comment]
LGTM.

**Comment by MingcongBai** [comment]
Clearly I did not see `perl` needs `db`, closing...
