### ISSUE TITLE
kernel: keep multi versions

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#25]
We need some serious use of PKGPROV.

**Comment by MingcongBai** [comment]
Wrong place, Linux Kernel is at https://github.com/AOSC-Dev/aosc-os-abbs ... Closing.

But as an additional note, we do support multi-kernel version inclusion right now.

**Comment by Artoria2e5** [comment]
Uh.. wut.. How about py then?

**Comment by MingcongBai** [comment]
Still, post an issue there...

Python won't work with different vendor path issue anyways. We will need a module build for each of the version if that's really what we are looking for.
