### ISSUE TITLE
gcc,clang,binutils (including optenv): symlink to /usr/bin/[target_triplet]-progname

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#27]
This will save us a lot of HOSTTOOLPREFIX bullshit.

**Comment by Artoria2e5** [comment]
? And binutils?

**Comment by MingcongBai** [comment]
https://github.com/AOSC-Dev/aosc-os-core/blob/90a5bb9e63878fda3b2cf516435be7ccdc957069/core-devel/binutils/autobuild/beyond#L5

**Comment by Artoria2e5** [comment]
Watch your quotes :/

CpyReq → os-abbs (optenv)

**Comment by MingcongBai** [comment]
> CpyReq → os-abbs (optenv)

That's an `aosc-os-abbs` issue. I will open that in a bit.

**Comment by MingcongBai** [comment]
> Watch your quotes :/

There's no spaces or anything in a triplet is there?

**Comment by Artoria2e5** [comment]
> There's no spaces or anything in a triplet is there?

Semantically sloppy,. Does unnecessary things.

**Comment by MingcongBai** [comment]
All right...
