### ISSUE TITLE
gcc: use profiled and LTO build

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#28]
"It is possible to use profile feedback to optimize the compiler itself. This should result in a faster compiler binary. Experiments done on x86 using gcc 3.3 showed approximately 7 percent speedup on compiling C programs. To bootstrap the compiler with profile feedback, use make profiledbootstrap.

When ‘make profiledbootstrap’ is run, it will first build a stage1 compiler. This compiler is used to build a stageprofile compiler instrumented to collect execution counts of instruction and branch probabilities. Then runtime libraries are compiled with profile collected. Finally a stagefeedback compiler is built using the information collected.

Unlike standard bootstrap, several additional restrictions apply. The compiler used to build stage1 needs to support a 64-bit integral type. It is recommended to only use GCC for this. "

["Installing GCC" documentation from GNU](https://gcc.gnu.org/install/build.html)

It is currently known that Fedora provides such a build with exceptions on the SPARC architectures, which we are not going to concern about in the near future XD. [Reference](http://pkgs.fedoraproject.org/cgit/rpms/gcc.git/tree/gcc.spec#n1060)

"‘bootstrap-lto’
    Enables Link-Time Optimization for host tools during bootstrapping. ‘BUILD_CONFIG=bootstrap-lto’ is equivalent to adding -flto to ‘BOOT_CFLAGS’. This option assumes that the host supports the linker plugin (e.g. GNU ld version 2.21 or later or GNU gold version 2.21 or later). "

Also an interesting configure option that we should look into. MIPS might run into issues with this, we will see about this. No other distributions are known to be using this option.

**Comment by MingcongBai** [comment]
Fixed with commit above. Will reopen when build failure is observed.

**Comment by liushuyu** [comment]
You can compile large projects to test it out. FYI, LMMS can test g++, while Linux kernel can fully test gcc 😃

**Comment by MingcongBai** [comment]
No, I meant the building of GCC itself...

**Comment by liushuyu** [comment]
Oh...
