### ISSUE TITLE
gcc: switch to new ABI

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#29]
Not doing a write up for now, but here are the things we know about at this point:
- Programs won't break immediately.
- A crap ton of rebuilds will be happenning this year.
- Further announcement and plan-of-attack on AOSCC (possibly workshop sessions).

**Comment by Artoria2e5** [comment]
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html and https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html.

The new ABI provides a new `std::string` impl, which is much faster than before.

**Comment by MingcongBai** [comment]
Thanks!

**Comment by Artoria2e5** [comment]
And https://stackoverflow.com/questions/1969916/ (useful for AOSC-Dev/aosc-os-abbs#119 too.)

**Comment by MingcongBai** [comment]
Currently we are still swinging upon this issue, a discussion will be held on Day 1 of AOSCC 2016.

**Comment by MingcongBai** [comment]
ABI update will be delayed indefinitely.

**Comment by Artoria2e5** [comment]
LLVM/clang 3.9 added support for emitting tagged mangled names for new ABI (g++ compatibility). Previously Archlinux used a patch from their code review system.

**Comment by Artoria2e5** [comment]
I think we should keep this open.

**Comment by jyhi** [comment]
Hi! As described in AOSC-Dev/aosc-os-abbs#1510, we are proceeding with this issue, and will perform the switch (along with the refactor) in Core 6.

**Comment by MingcongBai** [comment]
Done. Closing.
