### ISSUE TITLE
"bootstrap-O3" for gcc runtime?

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#32]

**Comment by MingcongBai** [comment]
Is this really a good idea though...?

**Comment by MingcongBai** [comment]
Adding onto that, I am still looking to build it with `bootstrap-lto`, as I mentioned before in #31.

```
Upstream bug reported, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70831.
```

I would hope to see what happens to that first (possibly after GCC 6.3 though, but we can always backport if we needed to).

**Comment by MingcongBai** [comment]
Closing this issue at the moment, wait till the LTO issue is sorted out then.
