### ISSUE TITLE
Switch to out-of-glibc libiconv, or patch glibc's iconv tables

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#43]
... Because

* cp950 is not Big5 (EUDC mappings)
* cp936 is not GBK (Euro sign)

**Comment by MingcongBai** [comment]
A patch sounds **slightly** more acceptable (before looking into the details). Please elaborate.

**Comment by Artoria2e5** [comment]
These are actually behavior differences from Windows for these supposedly Windows code pages... In cp950, MS mapped Big5's user-defined areas to Unicode's private areas; these PUA code points are in turn mandated by HKSCS standards for lower Unicode versions. In cp936, MS added a single-byte `\x80` euro sign `\u20AC` to GBK.

In glibc's implementation these code pages are set as aliases of their source encodings; given these MS modifications this is not a right thing to do.

**Comment by MingcongBai** [comment]
Ever bothered to file a bug report to Glibc?

**Comment by Artoria2e5** [comment]
I actually [blamed the standalone libiconv by mistake](https://lists.gnu.org/archive/html/bug-gnu-libiconv/2016-11/msg00010.html), so yes at least I have the test cases...

**Comment by MingcongBai** [comment]
What is the current status on this issue?

**Comment by Artoria2e5** [comment]
glibc fixed the problem in cp936 (targeted for 2.25), and is working on the cp950 issue.

**Comment by MingcongBai** [comment]
May i have a link to the original upstream report so I can see if there's any chance of backporting?

**Comment by Artoria2e5** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=20864

**Comment by MingcongBai** [comment]
Got it, thx.

**Comment by MingcongBai** [comment]
Fixed in Core 4.1. Closing.
