### ISSUE TITLE
gcc: Retpoline mitigation

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-core#58]
https://support.google.com/faqs/answer/7625886

**Comment by MingcongBai** [comment]
Will skip this for the upcoming Core 5.1 release, as changes are not yet upstream and it provides not a vulnerability fix (in fact, not a vulnerable software, at least not directly) - but to add extra flags to help with the current Spectre situations.

**Comment by MingcongBai** [comment]
Fixed with 6249a6851b1294977a05b5c69e47319091a294cf, and released with Core 5.1.1.

Please use AOSA-2018-0023.

**Comment by l2dy** [comment]
Use AOSA-2018-0023.
