### ISSUE TITLE
glibc: Unicode 8 support

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#7]
A change should be applied to `core-libs/glibc` (that I personally believe is beneficial enough to attempt...), Unicode 8.0 extension to the package.

The change is first originated from Fedora, and the change is explained here.

https://fedoraproject.org/wiki/Changes/Unicode_8.0

Patches for this change is already available.

https://sourceware.org/ml/libc-alpha/2015-06/msg00934.html

**Comment by Artoria2e5** [comment]
Wow, huge code table.

**Comment by MingcongBai** [comment]
@arthur2e5 you darn right it is.

**Comment by Artoria2e5** [comment]
Unicode and 8 reminded me -- although not really revelant -- of UTF-8 `C` locale which is found in musl. It seems that a way to archive a non-localized UTF-8 locale is using `C.UTF-8`. Maybe we should switch to it in some of our tools.

**Comment by MingcongBai** [comment]
Added patch and tested from https://github.com/AOSC-Dev/aosc-os-core/commit/e64dbfb95402c340ea885a5ef25f4a521878fda5.
