### ISSUE TITLE
perl: a (long-needed) version bump

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-core#8]
Perl was not updated since the start of AOSC OS3 project (August of 2014), due to the fact that Perl (site-)modules are installed in a versioned directory `/usr/lib/perl5/5.20.0/` and it is extremely time consuming to rebuild all of them modules.

A bump to Perl is advised in the near future, to the 5.22 series. However, it is not clear that if AOSC OS should rebuild the packages, or to make hacks (or even mask the directory as 5.20.0) in order for the Perl-based modules and packages to continue working.

**Comment by Artoria2e5** [comment]
Perhaps for the Beta period we can keep a mask there.

**Comment by MingcongBai** [comment]
Just shy of the time to open up the point-99 branch... going to have fun over there once GCC 6 is green.

**Comment by MingcongBai** [comment]
Bumped to 5.22.1 for Core 3.5.0. Closing.
